site_name: VDES 10918 | Interface 2 Navigation

extra_css:
    - css/style.css

pages:
    - Home: index.md
    - Lessons:
        - Week 1: week01/index.md
        - Week 2: week02/index.md
        - Week 3: week03/index.md
        - Week 4: week04/index.md
        - Week 5: week05/index.md
        
        - Week 6: week06/index.md
        - Week 7: week07/index.md
        - Week 8: week08/index.md
        - Week 9: week09/index.md
        - Week 11: week11/index.md
        - Week 12: week12/index.md
    - Projects: 
        - Project 1: projects/project01/readme.md
        - Project 2: projects/project02/readme.md
    - Firebird Setup: firebird/readme.md
    - Homework: homework/readme.md
